# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='title_link',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
