# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('watch_date', models.DateField(default=b'1900-01-01')),
                ('title_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
